import os


class Config:
    HTTP_PORT_BROKER = os.getenv("HTTP_PORT_BROKER")
    HTTP_PORT_SCRAPER = os.getenv("HTTP_PORT_SCRAPER")
    WIREGUARD_NETWORK_PREFIX = os.getenv("WIREGUARD_NETWORK_PREFIX")
    NODE_ID = 1

    ORIGIN_BROKER = f"http://{WIREGUARD_NETWORK_PREFIX}.{NODE_ID}:{HTTP_PORT_BROKER}"
    ORIGIN_SCRAPER = f"http://{WIREGUARD_NETWORK_PREFIX}.{NODE_ID}:{HTTP_PORT_SCRAPER}"
