import random
from collections.abc import Iterator
from itertools import cycle

URLS = [
    "https://example.com",
    "https://www.google.com",
    "https://www.youtube.com",
    "https://www.wikipedia.org",
    "https://www.reddit.com",
    "https://www.github.com",
    "https://www.stackoverflow.com",
    "https://www.microsoft.com",
    "https://www.apple.com",
    "https://www.amazon.com",
    "https://www.netflix.com",
    "https://www.linkedin.com",
    "https://www.instagram.com",
    "https://www.facebook.com",
    "https://www.x.com",
    "https://www.openai.com",
    "https://www.cloudflare.com",
    "https://www.mozilla.org",
    "https://www.python.org",
    "https://www.djangoproject.com",
    "https://fastapi.tiangolo.com",
    "https://httpx.readthedocs.io",
    "https://pydantic.dev",
    "https://docs.python.org",
    "https://www.gnu.org",
    "https://www.linux.org",
    "https://ubuntu.com",
    "https://www.debian.org",
    "https://archlinux.org",
    "https://www.kernel.org",
    "https://news.ycombinator.com",
    "https://techcrunch.com",
    "https://arstechnica.com",
    "https://www.theverge.com",
    "https://www.bbc.com",
    "https://www.cnn.com",
    "https://www.nytimes.com",
    "https://www.theguardian.com",
    "https://www.reuters.com",
    "https://apnews.com",
    "https://www.nasa.gov",
    "https://www.esa.int",
    "https://www.noaa.gov",
    "https://www.cern.ch",
    "https://www.nationalgeographic.com",
    "https://www.scientificamerican.com",
    "https://nature.com",
    "https://www.science.org",
    "https://www.harvard.edu",
    "https://www.mit.edu",
    "https://www.stanford.edu",
    "https://www.cam.ac.uk",
    "https://www.ox.ac.uk",
    "https://www.berkeley.edu",
    "https://www.princeton.edu",
    "https://www.yale.edu",
    "https://www.columbia.edu",
    "https://www.ucla.edu",
    "https://www.imdb.com",
    "https://www.rottentomatoes.com",
    "https://www.spotify.com",
    "https://soundcloud.com",
    "https://bandcamp.com",
    "https://www.twitch.tv",
    "https://vimeo.com",
    "https://archive.org",
    "https://www.flickr.com",
    "https://unsplash.com",
    "https://www.pixabay.com",
    "https://www.canva.com",
    "https://www.figma.com",
    "https://dribbble.com",
    "https://www.behance.net",
    "https://wordpress.org",
    "https://medium.com",
    "https://dev.to",
    "https://hashnode.com",
    "https://substack.com",
    "https://www.quora.com",
    "https://www.producthunt.com",
    "https://www.digitalocean.com",
    "https://www.heroku.com",
    "https://vercel.com",
    "https://netlify.com",
    "https://www.mongodb.com",
    "https://redis.io",
    "https://www.postgresql.org",
    "https://sqlite.org",
    "https://www.mysql.com",
    "https://kubernetes.io",
    "https://docker.com",
    "https://terraform.io",
    "https://grafana.com",
    "https://prometheus.io",
    "https://sentry.io",
    "https://www.jetbrains.com",
    "https://code.visualstudio.com",
    "https://gitlab.com",
    "https://bitbucket.org",
    "https://pypi.org",
    "https://www.npmjs.com",
    "https://crates.io",
]


class URLGenerator:
    URLS = URLS

    __cycle: Iterator[str] = cycle(URLS)

    @classmethod
    def next(cls) -> str:
        return next(cls.__cycle)

    @classmethod
    def rand(cls) -> str:
        return random.choice(cls.URLS)
