services:
  fastapi:
    build:
      context: ..
      dockerfile: scraper/Dockerfile
      args:
        CHROMIUM_VERSION: ${CHROMIUM_VERSION}
        CHROMIUM_SNAPSHOT_DATE: ${CHROMIUM_SNAPSHOT_DATE}
    env_file:
      - path: ../config.env
        required: true
    ports:
      - "${HTTP_PORT_SCRAPER}:8000"
    volumes:
      - ../scraper:/app/scraper
      - ../common:/app/common
      # Can not do a COPY inside the Dockerfile, as we are outside the component context
      # and that other services like NPM have limited permissions
      # And we mount outside of app as Docker tries to create an empty `plugins` folder inside of app
      # (but the simlink to the real plugins folder works)
      - ../plugins:/plugins:ro
      - /tmp/proxypi.sock:/tmp/proxypi.sock
    environment:
      NODE_ROLE: ${NODE_ROLE}
      PYTHONPATH: /app/scraper
    # Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarded.
    # deploy:
    #   resources:
    #     limits:
    #       cpus: ${SCRAPER_CPUS}
    #       memory: ${SCRAPER_MEMORY}
    # shm_size: ${SCRAPER_SHM_SIZE}
    restart: unless-stopped
    networks:
      - default

networks:
  default:
