services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT_SCRAPER}:8000"
    volumes:
      - ./:/app
      # Can not do a COPY inside the Dockerfile, as we are outside the component context
      # and that other services like NPM have limited permissions
      # And we mount outside of app as Docker tries to create an empty `plugins` folder inside of app
      # (but the simlink to the real plugins folder works)
      - ../plugins:/plugins:ro
      - /tmp/proxypi.sock:/tmp/proxypi.sock
    environment:
      NODE_ROLE: ${NODE_ROLE}
      # not sure if those are useful (those arguments are also set in main.py)
      # (which initiates the browser including those)
      CHROME_EXTRA_ARGS: >-
        --no-sandbox
        --disable-setuid-sandbox
    deploy:
      resources:
        limits:
          memory: 1800M
          cpus: '1.5'
        reservations:
          memory: 512M
    shm_size: '512mb'
    restart: unless-stopped
    networks:
      - default

networks:
  default:
