import datetime
import random
from uuid import UUID, uuid4

from contract.schemas.new_instance import NewInstanceRequest

from scraper.core.DatabaseHandler import DatabaseHandler
from scraper.core.models.DatabaseHandler import RecordProfile

SCRAPER_FIRST_NAMES = (
    "Noah",
    "Emma",
    "Liam",
    "Olivia",
    "Lucas",
    "Sophia",
    "Ethan",
    "Mia",
    "Leo",
    "Ava",
    "Jack",
    "Chloe",
    "Henry",
    "Lily",
    "Owen",
    "Zoe",
    "Felix",
    "Grace",
    "Max",
    "Ella",
    "Oscar",
    "Ruby",
    "Hugo",
    "Nora",
    "Theo",
    "Alice",
    "Arthur",
    "Clara",
    "Samuel",
    "Lucy",
    "Daniel",
    "Ivy",
    "Julian",
    "Hazel",
    "Nathan",
    "Rose",
    "Eli",
    "Stella",
    "Isaac",
    "Maya",
    "Gabriel",
    "Jade",
    "Adam",
    "Violet",
    "Caleb",
    "Iris",
    "Simon",
    "Luna",
    "Xavier",
    "Nina",
    "Oliver",
    "Eva",
    "Benjamin",
    "Julia",
    "Thomas",
    "Sadie",
    "David",
    "Molly",
    "Ryan",
    "Bella",
    "Alex",
    "Sophie",
    "Finn",
    "Elena",
    "Dylan",
    "Layla",
    "Aaron",
    "Naomi",
    "Victor",
    "Piper",
    "Jasper",
    "Aria",
    "Miles",
    "Cora",
    "Rowan",
    "Leah",
    "Sebastian",
    "Daphne",
    "Wesley",
    "Freya",
    "Connor",
    "Paige",
    "Evan",
    "Tessa",
    "Damian",
    "Holly",
    "Parker",
    "Skye",
    "Adrian",
    "Brooke",
    "Colin",
    "June",
    "Vincent",
    "Willa",
    "Tristan",
    "Faye",
    "Jonah",
    "Quinn",
    "Blake",
    "Avery",
)
SCRAPER_ADJECTIVES = (
    "Curious",
    "Sleepy",
    "Sparkling",
    "Mysterious",
    "Tiny",
    "Gigantic",
    "Sneaky",
    "Cheerful",
    "Grumpy",
    "Fearless",
    "Fluffy",
    "Electric",
    "Cosmic",
    "Wobbly",
    "Brilliant",
    "Silly",
    "Swift",
    "Moody",
    "Radiant",
    "Legendary",
    "Noisy",
    "Quiet",
    "Lucky",
    "Dramatic",
    "Epic",
    "Chaotic",
    "Noble",
    "Dazzling",
    "Frozen",
    "Fiery",
    "Golden",
    "Invisible",
    "Playful",
    "Stubborn",
    "Magical",
    "Reckless",
    "Clever",
    "Dreamy",
    "Jazzy",
    "Funky",
    "Sneezing",
    "Hungry",
    "Bouncy",
    "Glorious",
    "Spooky",
    "Daring",
    "Shiny",
    "Caffeinated",
    "Whimsical",
    "Wild",
    "Elegant",
    "Peculiar",
    "Fierce",
    "Goofy",
    "Hyperactive",
    "Melodic",
    "Secretive",
    "Thunderous",
    "Velvety",
    "Adventurous",
    "Quirky",
    "Vintage",
    "Galactic",
    "Prickly",
    "Heroic",
    "Fuzzy",
    "Regal",
    "Neon",
    "Wandering",
    "Lunar",
    "Solar",
    "Rainbow",
    "Turbocharged",
    "Cranky",
    "Sneaky-Beaky",
    "Philosophical",
    "Unstoppable",
    "Tactical",
    "Bewildered",
    "Marshmallowy",
    "Pirate-like",
    "Viking",
    "Baffling",
    "Determined",
    "Rogue",
    "Chill",
    "Boisterous",
    "Enchanted",
    "Mischievous",
    "Bewitching",
    "Absurd",
    "Glittering",
    "Squeaky",
    "Thunderstruck",
    "Majestic",
    "Witty",
    "Resilient",
    "Eccentric",
    "Zany",
    "Supreme",
)


class Profile(RecordProfile):
    profile_uuid: UUID
    profile_name: str
    created_at: datetime.datetime
    # browsing_history: ...

    @classmethod
    async def create(cls, request: NewInstanceRequest) -> "Profile":
        if not request.profile_uuid:
            instance = await cls.__create_profile()
            await DatabaseHandler.insert_record_profile(instance)
            return instance
        record_profile: RecordProfile = await DatabaseHandler.get_profile_from_uuid(
            request.profile_uuid
        )
        return cls.model_validate(record_profile.model_dump())

    @classmethod
    async def __create_profile(cls) -> "Profile":
        instance = cls(
            profile_uuid=uuid4(),
            profile_name=f"{random.choice(SCRAPER_ADJECTIVES)} {random.choice(SCRAPER_FIRST_NAMES)}",
            created_at=datetime.datetime.now(),
        )
        return instance
