import datetime
from typing import Annotated, Any, Dict, List, Literal, Tuple

from pydantic import BaseModel, Field, StringConstraints


class BrowserModel(BaseModel):
    window_size: Tuple[int, int]
    display: Annotated[str, StringConstraints(pattern=r"^:\d{3}$")]
    created_at: datetime.datetime
    expires_at: datetime.datetime
    remaining_lifespan: datetime.timedelta
    status: Literal["idle", "requesting", "spotted", "waiting"]
    score: float
    browser_history: List[Any]


class ScraperModel(BaseModel):
    browsers: Dict[str, BrowserModel] = Field(
        description=(
            "The key to the object is the `instance_id`: `str` of the browser. "
            "Those generated by the broker are composed of an adjective and a first name. "
        ),
    )
