import datetime
from typing import Any, Dict, List, Literal, Tuple

from pydantic import BaseModel, Field


class BrowserModel(BaseModel):
    window_size: Tuple[int, int]
    display: str
    created_at: datetime.datetime
    expires_at: datetime.datetime
    remaining_lifespan: datetime.timedelta
    status: Literal["idle", "requesting", "spotted", "waiting"]
    score: float
    browsing_history: List[Any]


class ScraperModel(BaseModel):
    is_running_as_root: bool
    can_create_browser: bool
    ram_specs: str
    ram_usage: str
    browsers: Dict[str, BrowserModel] = Field(
        description=(
            "The key to the object is the `instance_id`: `str` of the browser. "
            "Those generated by the broker are composed of an adjective and a first name. "
        ),
    )
