[project]
name = "ahoonepi-internal-interface"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "pydantic==2.12.5",
    "pydantic_core==2.41.5",
    "pydantic-settings==2.15.0",
    "zendriver==0.15.3",
    "fastapi==0.122.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/common",
    "src/contract",
    "src/proxypi_socket",
    "src/zendriver_ext",
]
