import ipaddress
import os


class Config:
    # the tests container loads this class but does not have the environment variables
    try:
        HTTP_PORT_SCRAPER = os.environ["HTTP_PORT_SCRAPER"]
        NODE_ROLE = os.environ["NODE_ROLE"].split(",")
        SSH_NETWORK_BASE = os.environ["SSH_NETWORK_BASE"]
        WIREGUARD_NETWORK_PREFIX = os.environ["WIREGUARD_NETWORK_PREFIX"]
    except Exception:
        pass

    ALLOWED_NETWORKS = [
        ipaddress.ip_network("127.0.0.0/8"),  # localhost
        # ipaddress.ip_network("10.0.0.0/24"),      # VPN network
        ipaddress.ip_network("10.0.0.1/32"),  # Lighthouse through VPN
        ipaddress.ip_network("172.16.0.0/12"),  # Docker bridge networks (for dev)
        ipaddress.ip_network(
            "192.168.0.0/16"
        ),  # Docker compose networks (for the proxypi socket)
        ipaddress.ip_network("::1/128"),  # IPv6 localhost
    ]

    BROKER_DATABASE = "/data/broker.db"
    BROKER_CLEAR_DB_ON_STARTUP = True
    DB_TABLE_TARGETS = "targets"
    DB_TABLE_REQUESTS = "jobs"
    DB_TABLE_LOGS = "logs"
    BUFFER_LOGGER_SIZE = 20
    LIMIT_SQL_QUERIES = 200
    REFRESH_PERIOD_BROKER = 1  # seconds
    THRESHOLD_SCORE = 300
    TRIGGER_LAZY_LOADING_BY_DEFAULT = True
    RETRIES = 3

    SCRAPER_FIRST_NAMES = (
        "Noah",
        "Emma",
        "Liam",
        "Olivia",
        "Lucas",
        "Sophia",
        "Ethan",
        "Mia",
        "Leo",
        "Ava",
        "Jack",
        "Chloe",
        "Henry",
        "Lily",
        "Owen",
        "Zoe",
        "Felix",
        "Grace",
        "Max",
        "Ella",
        "Oscar",
        "Ruby",
        "Hugo",
        "Nora",
        "Theo",
        "Alice",
        "Arthur",
        "Clara",
        "Samuel",
        "Lucy",
        "Daniel",
        "Ivy",
        "Julian",
        "Hazel",
        "Nathan",
        "Rose",
        "Eli",
        "Stella",
        "Isaac",
        "Maya",
        "Gabriel",
        "Jade",
        "Adam",
        "Violet",
        "Caleb",
        "Iris",
        "Simon",
        "Luna",
        "Xavier",
        "Nina",
        "Oliver",
        "Eva",
        "Benjamin",
        "Julia",
        "Thomas",
        "Sadie",
        "David",
        "Molly",
        "Ryan",
        "Bella",
        "Alex",
        "Sophie",
        "Finn",
        "Elena",
        "Dylan",
        "Layla",
        "Aaron",
        "Naomi",
        "Victor",
        "Piper",
        "Jasper",
        "Aria",
        "Miles",
        "Cora",
        "Rowan",
        "Leah",
        "Sebastian",
        "Daphne",
        "Wesley",
        "Freya",
        "Connor",
        "Paige",
        "Evan",
        "Tessa",
        "Damian",
        "Holly",
        "Parker",
        "Skye",
        "Adrian",
        "Brooke",
        "Colin",
        "June",
        "Vincent",
        "Willa",
        "Tristan",
        "Faye",
        "Jonah",
        "Quinn",
        "Blake",
        "Avery",
    )
    SCRAPER_ADJECTIVES = (
        "Curious",
        "Sleepy",
        "Sparkling",
        "Mysterious",
        "Tiny",
        "Gigantic",
        "Sneaky",
        "Cheerful",
        "Grumpy",
        "Fearless",
        "Fluffy",
        "Electric",
        "Cosmic",
        "Wobbly",
        "Brilliant",
        "Silly",
        "Swift",
        "Moody",
        "Radiant",
        "Legendary",
        "Noisy",
        "Quiet",
        "Lucky",
        "Dramatic",
        "Epic",
        "Chaotic",
        "Noble",
        "Dazzling",
        "Frozen",
        "Fiery",
        "Golden",
        "Invisible",
        "Playful",
        "Stubborn",
        "Magical",
        "Reckless",
        "Clever",
        "Dreamy",
        "Jazzy",
        "Funky",
        "Sneezing",
        "Hungry",
        "Bouncy",
        "Glorious",
        "Spooky",
        "Daring",
        "Shiny",
        "Caffeinated",
        "Whimsical",
        "Wild",
        "Elegant",
        "Peculiar",
        "Fierce",
        "Goofy",
        "Hyperactive",
        "Melodic",
        "Secretive",
        "Thunderous",
        "Velvety",
        "Adventurous",
        "Quirky",
        "Vintage",
        "Galactic",
        "Prickly",
        "Heroic",
        "Fuzzy",
        "Regal",
        "Neon",
        "Wandering",
        "Lunar",
        "Solar",
        "Rainbow",
        "Turbocharged",
        "Cranky",
        "Sneaky-Beaky",
        "Philosophical",
        "Unstoppable",
        "Tactical",
        "Bewildered",
        "Marshmallowy",
        "Pirate-like",
        "Viking",
        "Baffling",
        "Determined",
        "Rogue",
        "Chill",
        "Boisterous",
        "Enchanted",
        "Mischievous",
        "Bewitching",
        "Absurd",
        "Glittering",
        "Squeaky",
        "Thunderstruck",
        "Majestic",
        "Witty",
        "Resilient",
        "Eccentric",
        "Zany",
        "Supreme",
    )
