services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ../config.env
        required: true
    ports:
      - "${HTTP_PORT_BROKER}:8000"
    volumes:
      - ./:/app
      - ./data:/data
      # - sqlite_data:/data
      - ../plugins:/plugins:ro
      - ../common:/common:ro
      - /tmp/proxypi.sock:/tmp/proxypi.sock
    environment:
      NODE_ROLE: ${NODE_ROLE}
    restart: unless-stopped
    networks:
      - default

# volumes:
#   sqlite_data:
#     driver: local

networks:
  default:
