import datetime
from typing import Literal

from pydantic import BaseModel, Field, HttpUrl


class BrowsingRecord(BaseModel):
    url: HttpUrl
    status: Literal["aborted", "blocked", "failed", "success"] | None = None
    timestamp: datetime.datetime | None = None
    tab_state: Literal["complete", "interactive", "loading"] | None = None
    success_lazy_loading: bool | None = None
    error: str | None = None
    html: str | None = None


class BrowserModel(BaseModel):
    window_size: tuple[int, int]
    display: str
    created_at: datetime.datetime
    expires_at: datetime.datetime
    remaining_lifespan: datetime.timedelta
    status: Literal["idle", "requesting", "spotted", "waiting"]
    score: float
    browsing_history: list[BrowsingRecord]


class ScraperModel(BaseModel):
    is_running_as_root: bool
    can_create_browser: bool
    ram_specs: str
    ram_usage: str
    browsers: dict[str, BrowserModel] = Field(
        description=(
            "The key to the object is the `instance_id`: `str` of the browser. "
            "Those generated by the broker are composed of an adjective and a first name. "
        ),
    )
